CREATE DATABASE IF NOT EXISTS kasir_makeup;
USE kasir_makeup;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY, nama VARCHAR(100) NOT NULL,
  username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL,
  role ENUM('admin','cashier') NOT NULL DEFAULT 'cashier');
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY, kode_barang VARCHAR(50) UNIQUE NOT NULL,
  nama_barang VARCHAR(150) NOT NULL, kategori VARCHAR(50),
  harga INT NOT NULL, stok INT NOT NULL DEFAULT 0, foto LONGTEXT NULL);
CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY, nama VARCHAR(100) NOT NULL, no_telp VARCHAR(20) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY, no_struk VARCHAR(30) UNIQUE NOT NULL,
  tanggal DATETIME DEFAULT CURRENT_TIMESTAMP, user_id INT NOT NULL, member_id INT NULL,
  metode_bayar VARCHAR(20) NOT NULL, total INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (member_id) REFERENCES members(id));
CREATE TABLE IF NOT EXISTS transaction_items (
  id INT AUTO_INCREMENT PRIMARY KEY, transaction_id INT NOT NULL, product_id INT NOT NULL,
  jumlah INT NOT NULL, harga_satuan INT NOT NULL, subtotal INT NOT NULL,
  FOREIGN KEY (transaction_id) REFERENCES transactions(id), FOREIGN KEY (product_id) REFERENCES products(id));